// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function RequestFrame() {
  return window['go']['main']['App']['RequestFrame']();
}

export function SetButtonA(arg1) {
  return window['go']['main']['App']['SetButtonA'](arg1);
}

export function SetButtonB(arg1) {
  return window['go']['main']['App']['SetButtonB'](arg1);
}

export function SetButtonDown(arg1) {
  return window['go']['main']['App']['SetButtonDown'](arg1);
}

export function SetButtonLeft(arg1) {
  return window['go']['main']['App']['SetButtonLeft'](arg1);
}

export function SetButtonRight(arg1) {
  return window['go']['main']['App']['SetButtonRight'](arg1);
}

export function SetButtonSelect(arg1) {
  return window['go']['main']['App']['SetButtonSelect'](arg1);
}

export function SetButtonStart(arg1) {
  return window['go']['main']['App']['SetButtonStart'](arg1);
}

export function SetButtonUp(arg1) {
  return window['go']['main']['App']['SetButtonUp'](arg1);
}
