// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function InitializeInputListeners() {
  return window['go']['main']['App']['InitializeInputListeners']();
}

export function ReadA() {
  return window['go']['main']['App']['ReadA']();
}

export function ReadB() {
  return window['go']['main']['App']['ReadB']();
}

export function ReadDown() {
  return window['go']['main']['App']['ReadDown']();
}

export function ReadLeft() {
  return window['go']['main']['App']['ReadLeft']();
}

export function ReadRight() {
  return window['go']['main']['App']['ReadRight']();
}

export function ReadSelect() {
  return window['go']['main']['App']['ReadSelect']();
}

export function ReadStart() {
  return window['go']['main']['App']['ReadStart']();
}

export function ReadUp() {
  return window['go']['main']['App']['ReadUp']();
}

export function RequestFrame() {
  return window['go']['main']['App']['RequestFrame']();
}
