// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function RequestFrame():Promise<any>;

export function SetButtonA(arg1:boolean):Promise<void>;

export function SetButtonB(arg1:boolean):Promise<void>;

export function SetButtonDown(arg1:boolean):Promise<void>;

export function SetButtonLeft(arg1:boolean):Promise<void>;

export function SetButtonRight(arg1:boolean):Promise<void>;

export function SetButtonSelect(arg1:boolean):Promise<void>;

export function SetButtonStart(arg1:boolean):Promise<void>;

export function SetButtonUp(arg1:boolean):Promise<void>;
