// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function InitializeInputListeners():Promise<void>;

export function ReadA():Promise<void>;

export function ReadB():Promise<void>;

export function ReadDown():Promise<void>;

export function ReadLeft():Promise<void>;

export function ReadRight():Promise<void>;

export function ReadSelect():Promise<void>;

export function ReadStart():Promise<void>;

export function ReadUp():Promise<void>;

export function RequestFrame():Promise<any>;
