name: prettier
run-name: prettier
on:
  push:
    branches:
      - master
jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version-file: 'internal/standalone/frontend/package.json'
      - run: npm ci
        working-directory: ./internal/standalone/frontend
      - run: npx prettier . --check
        working-directory: ./internal/standalone/frontend
